(ns chipper-chaps-chateau.boards.colored1)

(def board [{:chip/color :yellow, :point [1 1 1]}
            {:chip/color :green, :point [1 1 2]}
            {:chip/color :yellow, :point [1 1 3]}
            {:chip/color :red, :point [1 2 1]}
            {:chip/color :yellow, :point [1 2 2]}
            {:chip/color :red, :point [1 2 3]}
            {:chip/color :blue, :point [1 3 1]}
            {:chip/color :yellow, :point [1 3 2]}
            {:chip/color :blue, :point [1 3 3]}
            {:chip/color :blue, :point [2 1 1]}
            {:chip/color :green, :point [2 1 2]}
            {:chip/color :blue, :point [2 1 3]}
            {:chip/color :blue, :point [2 2 1]}
            {:chip/color :red, :point [2 2 2]}
            {:chip/color :green, :point [2 2 3]}
            {:chip/color :green, :point [2 3 1]}
            {:chip/color :blue, :point [2 3 2]}
            {:chip/color :green, :point [2 3 3]}
            {:chip/color :green, :point [3 1 1]}
            {:chip/color :red, :point [3 1 2]}
            {:chip/color :green, :point [3 1 3]}
            {:chip/color :yellow, :point [3 2 1]}
            {:chip/color :red, :point [3 2 2]}
            {:chip/color :yellow, :point [3 2 3]}
            {:chip/color :red, :point [3 3 1]}
            {:chip/color :blue, :point [3 3 2]}
            {:chip/color :red, :point [3 3 3]}])
(def board2 [{:chip/color :blue, :point [1 1 1]}
             {:chip/color :blue, :point [1 1 2]}
             {:chip/color :yellow, :point [1 1 3]}
             {:chip/color :red, :point [1 2 1]}
             {:chip/color :red, :point [1 2 2]}
             {:chip/color :blue, :point [1 2 3]}
             {:chip/color :red, :point [1 3 1]}
             {:chip/color :red, :point [1 3 2]}
             {:chip/color :blue, :point [1 3 3]}
             {:chip/color :blue, :point [2 1 1]}
             {:chip/color :blue, :point [2 1 2]}
             {:chip/color :yellow, :point [2 1 3]}
             {:chip/color :blue, :point [2 2 1]}
             {:chip/color :red, :point [2 2 2]}
             {:chip/color :green, :point [2 2 3]}
             {:chip/color :green, :point [2 3 1]}
             {:chip/color :green, :point [2 3 2]}
             {:chip/color :red, :point [2 3 3]}
             {:chip/color :yellow, :point [3 1 1]}
             {:chip/color :yellow, :point [3 1 2]}
             {:chip/color :green, :point [3 1 3]}
             {:chip/color :yellow, :point [3 2 1]}
             {:chip/color :yellow, :point [3 2 2]}
             {:chip/color :green, :point [3 2 3]}
             {:chip/color :green, :point [3 3 1]}
             {:chip/color :green, :point [3 3 2]}
             {:chip/color :red, :point [3 3 3]}])
